name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build CCExtractor on Windows", "Build CCExtractor on Linux"]
    types:
      - completed

jobs:
  start_ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
